name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3.1.0

    - name: DNS Test
      #run: go test -v ./...
      # it is easier for now to run these set of tests in docker
      # otherwise we would need to manipulate the /etc/resolv.conf
      # in the github actions container
      run: docker build -t host-resolver:latest . && docker run --dns 127.0.0.1 -it host-resolver:latest
